service: olive
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    TOKEN: ${env:TOKEN}
    QRCODE_BUCKET_NAME: ${env:QRCODE_BUCKET_NAME}
    QRCODE_TABLE_NAME: ${env:QRCODE_TABLE_NAME}
    ENVIRONMENT: ${env:ENVIRONMENT}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:PutObject'
          Resource:
            Fn::Join:
              - '/'
              - - "Fn::GetAtt": [ oliveQRCodes, Arn ]
                - '*'
        - Effect: Allow
          Action:
           - "dynamodb:PutItem"
           - "dynamodb:GetItem"
           - "dynamodb:Query"
          Resource:
            - "Fn::GetAtt": [ oliveQRCodesTable, Arn ]

resources:
  Resources:
    oliveQRCodes:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: olive-qr-codes
    oliveQRCodesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: olive-qr-codes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: S
          - AttributeName: "createdAt"
            AttributeType: N
        KeySchema:
          - AttributeName: "id"
            KeyType: HASH
          - AttributeName: "createdAt"
            KeyType: RANGE


functions:
  api:
    handler: src/qrcode/index.handler
    events:
      - httpApi:
          path: /qrcode/{id}
          method: get

  qrcodeApi:
    handler: src/qrcode/index.qrcodeHandler
    events:
      - httpApi:
          path: /qrcode
          method: post
  
  ddbotInteractions:
    handler: src/ddbot/index.interactionHandler
    events:
      - httpApi:
          path: /interactions
          method: post
  
  gaForm:
    handler: src/ga-automation/index.formSubmitHandler
    events:
      - httpApi:
          path: /ga/form
          method: post
  
  health:
    handler: src/ga-automation/index.health
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
