service: olive
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    TOKEN: ${env:TOKEN}
    QRCODE_BUCKET_NAME: ${env:QRCODE_BUCKET_NAME}
    QRCODE_TABLE_NAME: ${env:QRCODE_TABLE_NAME}
    ENVIRONMENT: ${env:ENVIRONMENT}
    GA_FORM_SUBMITION_QUEUE_URL:
      Fn::GetAtt:
        - gaFormSubmition
        - QueueUrl
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:PutObject"
          Resource:
            Fn::Join:
              - "/"
              - - "Fn::GetAtt": [oliveQRCodes, Arn]
                - "*"
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:Query"
          Resource:
            - "Fn::GetAtt": [oliveQRCodesTable, Arn]
            - "Fn::GetAtt": [gaToursTable, Arn]
        - Effect: Allow
          Action:
            - "sqs:SendMessage"
            - "sqs:ReceiveMessage"
          Resource:
            - "Fn::GetAtt": [gaFormSubmition, Arn]

resources:
  Resources:
    oliveQRCodes:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: olive-qr-codes
    oliveQRCodesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: olive-qr-codes
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: S
          - AttributeName: "createdAt"
            AttributeType: N
        KeySchema:
          - AttributeName: "id"
            KeyType: HASH
          - AttributeName: "createdAt"
            KeyType: RANGE
    gaFormSubmition:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ga-form-submition
    gaToursTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ga-tours
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "tourDate"
            AttributeType: S
          - AttributeName: "tourName"
            AttributeType: S
        KeySchema:
          - AttributeName: "tourDate"
            KeyType: HASH
          - AttributeName: "tourName"
            KeyType: RANGE

functions:
  gaForm:
    handler: src/ga-automation/index.formSubmitHandler
    events:
      - httpApi:
          path: /ga/form
          method: post
  gaFormMessage:
    handler: src/ga-automation/index.formSubmitMessageHandler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - gaFormSubmition
              - Arn

  health:
    handler: src/ga-automation/index.health
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline-sqs
  - serverless-offline

custom:
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: "2012-11-05"
    endpoint: http://0.0.0.0:9324
    region: eu-west-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
